# mosquitto.conf
persistence true
persistence_location /mosquitto/data/
log_dest stdout

# MQTT Listener port
listener 1883

# WebSocket listener
listener 9001
protocol websockets

allow_anonymous true